version: '3'
services:
  backend:
    image: "settraces/backend:backend"
    env_file:
      backend.env
    ports:
      - 8080:8080
    links:
      - database
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data: # named volumes can be managed easier using docker-compose
